name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[routes]]
pattern = "mail.cute2.top"

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "5dc92441-d247-4d0f-9e4d-8cee604b6b23"

[[kv_namespaces]]
binding = "kv"
id = "985d97b82ca947d1ac28b2c756a4d506"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloud-mail"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
orm_log = false
domain = ["cute2.top"]
admin = "admin@cute2.top"
jwt_secret = "cute2-cloudmail-k7m2x9p4q8w3"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
